# This workflow automatically merges changes from the main branch to the gh-pages branch.
# This ensures that the deployed GitHub Pages site is always up-to-date with the latest code.
# The workflow runs whenever changes are pushed to the main branch.


name: Auto Merge Main to GH-Pages

on:
  push:
    branches:
      - main

jobs:
  merge-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
      - name: Merge Main to GH-Pages
        run: |
          # Check if gh-pages branch exists
          if git ls-remote --heads origin gh-pages | grep gh-pages; then
            echo "GH-Pages branch exists, proceeding with merge"
          else
            echo "GH-Pages branch does not exist, creating it"
            git checkout -b gh-pages
            git push -u origin gh-pages
            git checkout main
          fi
          
          # Merge main into gh-pages
          git checkout gh-pages
          git pull origin gh-pages
          git merge origin/main -m "Auto-merge main into gh-pages"
          git push origin gh-pages
